# Use the official Node.js 16 image from Docker Hub
FROM node:20-alpine
# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN npm install --g pnpm

RUN pnpm install

# Copy the rest of your app's source code
COPY . .

ENV NODE_ENV=development

# Expose port 3000 for the app
EXPOSE 3000

# Start the app
CMD [ "pnpm", "dev" ]
