# Use the official Node.js 16 image from Docker Hub
FROM node:20-alpine

RUN npm install --g pnpm

# rootdir

WORKDIR /app

COPY ../package.json ./

RUN pnpm install

COPY ../common ./common


# frontend

WORKDIR /app/frontend

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

ENV NODE_ENV=development

# Expose port 3000 for the app
EXPOSE 3000

# Start the app
CMD [ "pnpm", "dev" ]
