version: '3.8'

x-common-env: &x-common-env
  ENVIRONMENT: "development"
  NODE_ENV: "development"
  BACKEND_HOST: "${BACKEND_HOST:-}"
  BACKEND_PORT: "${BACKEND_PORT:-8000}"
  FRONTEND_PORT: "${FRONTEND_PORT:-}"
  FRONTEND_API_URL: "${FRONTEND_API_URL}"

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
    env_file:
      - .env
    environment:
      <<: *x-common-env
    # networks:
    #   mongo_net:
    #     ipv4_address: 172.16.0.1
    # command: mongod --bind_ip 127.0.0.1,172.16.0.1

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "${DOCKER_FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      <<: *x-common-env
