version: '3.8'

x-common-env: &x-common-env
  ENVIRONMENT: "development"
  NODE_ENV: "development"
  BACKEND_HOST: "${BACKEND_HOST:-}"
  BACKEND_PORT: "${BACKEND_PORT:-8000}"
  FRONTEND_PORT: "${FRONTEND_PORT:-}"
  FRONTEND_API_URL: "${FRONTEND_API_URL}"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ./common:/app/common
      - ./backend:/app/backend
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
    env_file:
      - .env
    environment:
      <<: *x-common-env
    # networks:
    #   level_7_network:
    #     ipv4_address: 172.18.0.22

  frontend:
    restart: always
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - ./common:/app/common
      - ./frontend:/app/frontend
    ports:
      - "${DOCKER_FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      <<: *x-common-env
    depends_on:
      - backend
    # networks:
    #   - level_7_network

    # networks:
    #   level_7_network:
    #     driver: bridge
    #     ipam:
    #       config:
    #         - subnet: 172.18.0.0/16
