# Use an official Node.js runtime as a parent image
FROM node:20-alpine

RUN npm install -g pnpm

# # rootdir

WORKDIR /app

COPY ../package.json ./

RUN pnpm install

COPY ../common ./common

# backend dir

WORKDIR /app/backend

COPY package.json ./

RUN pnpm install

COPY . .

ENV NODE_ENV=development

EXPOSE 8000

CMD ["pnpm", "dev"]